swagger: '2.0'
info:
  title: Picker Production Documentation accounting cards API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
host: api.pickerexpress.com
basePath: /
schemes:
- http
tags:
- name: cards
paths:
  /customer/list/card:
    get:
      summary: list of cards
      operationId: getCustomerListCard
      parameters:
      - type: string
        description: Bearer Token
        name: authorization
        in: header
        required: true
      - type: string
        description: en/ar
        name: content-language
        in: header
        required: true
      consumes:
      - application/x-www-form-urlencoded
      tags:
      - cards
      responses:
        default:
          schema:
            type: string
          description: Successful
