openapi: 3.2.0
info:
  title: Picker Production Documentation Shopify API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Shopify
paths:
  /api/pushShopifyOrder:
    post:
      summary: Handle shopify integration with push system
      operationId: postApiPushshopifyorder
      tags:
      - Shopify
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
  /api/saveShopifyConfig:
    post:
      summary: Handle shopify integration with push system
      operationId: postApiSaveshopifyconfig
      tags:
      - Shopify
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
