openapi: 3.2.0
info:
  title: Picker Production Documentation Integrations API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Integrations
paths:
  /user/integrationUsers:
    get:
      summary: Get API users with external integrations
      operationId: getUserIntegrationusers
      tags:
      - Integrations
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
