openapi: 3.2.0
info:
  title: Picker Production Documentation Busy API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: busy
paths:
  /driver/clearDriver:
    put:
      summary: To unstuck driver
      operationId: putDriverCleardriver
      parameters:
      - description: Bearer Token
        name: authorization
        in: header
        required: true
        schema:
          type: string
      - description: en/ar
        name: content-language
        in: header
        required: true
        schema:
          type: string
      - description: Driver user id
        name: userID
        in: query
        required: true
        schema:
          type: string
      tags:
      - busy
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
