openapi: 3.2.0
info:
  title: Picker Production Documentation Datil API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: datil
paths:
  /datil/receiptIssued:
    post:
      summary: Webhook for receipt-issued notification of Datil
      operationId: postDatilReceiptissued
      tags:
      - datil
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
