openapi: 3.2.0
info:
  title: Picker Production Documentation Chatbot API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Chatbot
paths:
  /api/sendChatbotBookingRate:
    post:
      summary: Rating a booking from chatbot
      operationId: postApiSendchatbotbookingrate
      parameters:
      - description: Bearer Token
        name: authorization
        in: header
        required: true
        schema:
          type: string
      - description: en/ar
        name: content-language
        in: header
        required: true
        schema:
          type: string
      tags:
      - Chatbot
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Model_59'
components:
  schemas:
    Model_59:
      type: object
      properties:
        title:
          type: string
        bookingID:
          type: string
        rating:
          type: string
        comment:
          type: string
        workspaceName:
          type: string
        businessName:
          type: string
        customerName:
          type: string
      required:
      - bookingID
      - rating
      - comment
