openapi: 3.2.0
info:
  title: Picker Production Documentation Health Check API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Health Check
paths:
  /health-check:
    get:
      summary: Get health check
      operationId: getHealthcheck
      tags:
      - Health Check
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
