openapi: 3.2.0
info:
  title: Picker Production Documentation Vtex API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: vtex
paths:
  /api/pushVtexOrder:
    post:
      summary: Handle vtex integration with push system
      operationId: postApiPushvtexorder
      tags:
      - vtex
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
