swagger: '2.0'
info:
  title: Picker Production Documentation accounting spoonity API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
host: api.pickerexpress.com
basePath: /
schemes:
- http
tags:
- name: spoonity
paths:
  /api/pushSpoonityOrder:
    post:
      summary: Handle spoonity integration with push system
      operationId: postApiPushspoonityorder
      tags:
      - spoonity
      responses:
        default:
          schema:
            type: string
          description: Successful
