openapi: 3.2.0
info:
  title: Picker Production Documentation Cancel API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Cancel
paths:
  /cancel:
    get:
      summary: Get All Cancel Request
      operationId: getCancel
      parameters:
      - description: Bearer Token
        name: authorization
        in: header
        required: true
        schema:
          type: string
      - description: en/ar
        name: content-language
        in: header
        required: true
        schema:
          type: string
      - name: bookingId
        in: query
        required: false
        schema:
          type: string
      tags:
      - Cancel
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
