openapi: 3.2.0
info:
  title: Picker Production Documentation Accounting API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Accounting
paths:
  /accounting/refundBalanceTransactions:
    put:
      summary: Registers transaction refund for the selected balance transactions
      operationId: putAccountingRefundbalancetransactions
      parameters:
      - description: Bearer Token
        name: authorization
        in: header
        required: true
        schema:
          type: string
      - description: en/ar
        name: content-language
        in: header
        required: true
        schema:
          type: string
      tags:
      - Accounting
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Model_2'
components:
  schemas:
    transactions:
      type: array
      items:
        type: string
    Model_2:
      type: object
      properties:
        transactions:
          $ref: '#/components/schemas/transactions'
          type: array
      required:
      - transactions
