openapi: 3.2.0
info:
  title: Picker Production Documentation Pause API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: Pause
paths:
  /booking/play/pause:
    put:
      summary: start time and pause time
      operationId: putBookingPlayPause
      parameters:
      - description: Bearer Token
        name: authorization
        in: header
        required: true
        schema:
          type: string
      - description: en/ar
        name: content-language
        in: header
        required: true
        schema:
          type: string
      tags:
      - Pause
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Model_44'
components:
  schemas:
    Model_44:
      type: object
      properties:
        bookingID:
          type: string
          description: enter booking ID for which play pause going on is to be made
        startTime:
          type: boolean
      required:
      - bookingID
      - startTime
