openapi: 3.2.0
info:
  title: Picker Production Documentation Spoonity API
  version: V1.0.0
  contact:
    name: RV
    email: rachit.verma@nextjuggernaut.com
servers:
- url: http://api.pickerexpress.com/
tags:
- name: spoonity
paths:
  /api/pushSpoonityOrder:
    post:
      summary: Handle spoonity integration with push system
      operationId: postApiPushspoonityorder
      tags:
      - spoonity
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
